### PR TITLE
feat(jar): Adds :scm-url option to jar

### LINKED ISSUE #1: Add in :scm-url as a keyword to jar
Cljdoc wants the url of the scm target to parse out articles, so this needs to get added into the POM. This is the `:url` key under `:scm` in `clojure.tools.build.api/write-pom`. A key like `:scm-url` in `(jar ..)` would be nice.

### PR DESCRIPTION
**Pull request by kiranshila**
Fixes #1

### CODE REVIEW

**Comment by seancorfield** [comment]
Given that `tools.build` already has that ability and I'm hoping to sunset `depstar` in favor of `tools.build` as soon as the latter's `uber` task has parity with `depstar`'s merging functionality, I'm not going to add this.

**Comment by seancorfield** [comment]
I think the better option would be to just let users pass the whole `:scm` structure through. I implemented `:tag` because that was all my current projects use, so this needs a more holistic approach.

**Comment by kiranshila** [comment]
> I think the better option would be to just let users pass the whole `:scm` structure through. I implemented `:tag` because that was all my current projects use, so this needs a more holistic approach.

Fair enough! Thanks for taking a look.

**Comment by seancorfield** [comment]
For the historical record, this was implemented in v0.1.1 d096192

**Pull request closed without merging**
