### PR TITLE
Implements issue #8: add help command

### PR DESCRIPTION
**Pull request by pmonks**
This PR provides a first-cut implementation of issue #8.  Comments welcome!

### CODE REVIEW

**Comment by pmonks** [comment]
Example output for one of my own projects:

```
$ clj -T:build help
This is the build script for futbot.
-------------------------
build/check
([opts])
  Check the code by compiling it.
-------------------------
build/clean
([opts])
  Clean up the project.
-------------------------
build/eastwood
([opts])
  Run the eastwood linter.
-------------------------
build/gen-ist-markov
([opts])
  (Re)generate the IST Markov chain.
-------------------------
build/help
([_])
  Display this help message.
-------------------------
build/kondo
([opts])
  Run the clj-kondo linter.
-------------------------
build/lint
([opts])
  Run all linters.
-------------------------
build/outdated
([opts])
  Check for outdated dependencies.
-------------------------
build/run
([opts])
  Run the bot from source.
-------------------------
build/run-uber
([opts])
  Build the bot's uberjar, and run it.
-------------------------
build/uber
([opts])
  Create an uber jar.
```

**Comment by seancorfield** [comment]
You know that you can just run this to get help on any `build.clj` file?

```bash
clojure -A:deps -T:build help/doc
```

I'll add a note to the readme.

**Comment by pmonks** [comment]
> You know that you can just run this to get help on any `build.clj` file?

I did not, despite looking for it in both tools.build & build-clj docs.

> I'll add a note to the readme.

Perfect!

**Comment by seancorfield** [comment]
It's documented here: https://clojure.org/reference/deps_and_cli#_help_functions

**Comment by pmonks** [comment]
> It's documented here: [clojure.org/reference/deps_and_cli#_help_functions](https://clojure.org/reference/deps_and_cli#_help_functions)

Thanks. Didn't think to look for documentation on `tools.build` features in the `tools.deps` docset...

And yes, I know _now_ that those helper fns are for all tools (not just `tools.build`), but that's not something I would expect many folks just starting out with `tools.build` to figure out. Anyhoo, that's not a `build-clj` problem...

**Comment by seancorfield** [comment]
Yeah, I have been adding it as a comment in `build.clj` files in my OSS projects because I don't think many people have followed the #tools-deps discussions on Slack either (where this has come up a few times). For example: https://github.com/seancorfield/next-jdbc/blob/develop/build.clj#L12

**Pull request closed without merging**
